name: Health Check

run-name: Web Server Health Check

on:
  schedule:
    - cron: '35 20 * * *'

jobs:
    health-check:
      runs-on: ubuntu-20.04
      steps:
        - name: Check the deployed service URL
          uses: jtalk/url-health-check-action@v3
          with:
            url: https://phonebookcd.onrender.com

        - name: Test Success
          uses: rjstone/discord-webhook-notify@v1
          if: success()
          with:
              severity: info
              details: Test Succeeded :) Tada!
              webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}

        - name: Test Failure
          uses: rjstone/discord-webhook-notify@v1
          if: failure()
          with:
              severity: error
              details: Test Failed :( ohn!
              webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}